# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Thibault Coupin'
tagline:          'Mon bloc note'
description:      'Des notes, des trucs, mon bordel quoi.'
url:              'https://tcoupin.github.io'
baseurl:          /
mytheme:            'theme-base-0d'

author:
  name:           'Thibault Coupin'
  twitter:        thibbojunior
  github:         tcoupin

#paginate:         5
