# Site settings
title: Thibault Coupin
header-img: img/home-bg.jpg
email: thibault.coupin@gmail.com
description: "Le bloc note de Thibault Coupin"
baseurl: ""
url: "http://tcoupin.github.io"
twitter_username: thibbojunior
github_username:  tcoupin
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]
